# Generated by Django 2.0.7 on 2018-08-30 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 18, 37, 13, 568706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 18, 37, 13, 568706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3),
        ),
    ]
