# Generated by Django 2.0.7 on 2018-08-30 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180830_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 19, 7, 18, 819666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 19, 7, 18, 819666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
