# Generated by Django 2.1.2 on 2018-10-14 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20180830_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='image',
        ),
        migrations.AlterField(
            model_name='flight',
            name='arriving_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
